dataset:
  test:
    name: image_only
    root: "/mnt/work/users/david.anglada/datasets/ki67_coco/split/"  # Path to the test dataset
    fold: case_50140_image_only
    num_classes: 3                   # Fold to use for testing

loader:
  test:
    shuffle: False
    batch_size: 1
    num_workers: 1
    drop_last: False

optimizer:
  lr: 0.0002
  epochs: 100
  weight_decay: 0.0001
  max_norm: 0.1

model:
  encoder_name: resnext50_32x4d 
  classes_s: 3                   
  classes_c: 1                    
  encoder_weights: imagenet      
  decoder_channels: [256, 128, 64, 32, 16] 
  decoder_use_batchnorm: True

training:
  sigma: 5
  th: 0.15

transforms:
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

distributed: True

evaluation:
  thresholds: [0.5]
  max_pair_distance: 12
  interval: 1   

experiment:
  wandb: True
  project: "DualU-Net_repo"
  name: "ki67-combined-50140_epoch_100.pth" 
  wandb_group: "test"
  seed: 42
  output_dir: /mnt/work/users/david.anglada/dualunet/checkpoints/ki67/
  output_name: "ki67-combined-50140_epoch_100.pth"
